---
author: ""
output:
  html_document:
  css: style.css

---


<p align = "justify">

<font size="4"> Data analysis for: </font>

<font size="5">Evolution of cell size and growth in Prokaryotes</font>
</p>

</p></p>

[Dylan J. Padilla Perez](https://dylanpadilla.netlify.app/), School of Life Sciences, Arizona State University, Tempe, AZ 85287, USA.
</p></p>



```{r, include = FALSE}

knitr::opts_chunk$set(comment = ">", fig.width = 7, fig.height = 7, dpi = 300)

```

<b>
<font size="5"> Library </font>
</b>

```{r}

library(ape)
library(geiger)
library(DESeq2)
library(phytools)
library(phylolm)
library(lattice)
library(nlme)
library(raster)
library(scales)
library(vioplot)


```


<b>
<font size="5"> Loading the data </font>
</b>



```{r}


tree <- read.tree("spp.tree.nwk")
tree
#tree$tip.label

##plotTree(tree, type = "fan", ftype = "off")


data <- read.csv("condensed_traits_NCBI.csv")
str(data)
names(data)

spp.d1_lo <- data[!is.na(data$d1_lo), ]
spp.d1_up <- data[!is.na(data$d1_up), ]
spp.doubling <- data[!is.na(data$doubling_h), ]
spp.rRNA <- data[!is.na(data$rRNA16S_genes), ]
spp.tRNA <- data[!is.na(data$tRNA_genes), ]


tRNA <- aggregate(spp.tRNA$tRNA_genes, by = list(spp.tRNA$species), mean, na.action = na.rm)
rRNA <- aggregate(spp.rRNA$rRNA16S_genes, by = list(spp.rRNA$species), mean, na.action = na.rm)
d1_up <- aggregate(spp.d1_up$d1_up, by = list(spp.d1_up$species), mean, na.action = na.rm)
d1_lo <- aggregate(spp.d1_lo$d1_lo, by = list(spp.d1_lo$species), mean, na.action = na.rm)
doubling <- aggregate(spp.doubling$doubling_h, by = list(spp.doubling$species), mean, na.action = na.rm)


dim(tRNA)
names(tRNA) <- c("species", "tRNA")
dim(rRNA)
names(rRNA) <- c("species", "rRNA")
dim(d1_up)
names(d1_up) <- c("species", "d1_up")
dim(d1_lo)
names(d1_lo) <- c("species", "d1_lo")
dim(doubling)
names(doubling) <- c("species", "doubling_h")



```


<b>
<font size="5"> Evolutionary relationship between growth and size </font>
</b>



```{r}


size.growth <- merge(doubling, d1_up, by = "species")


obj <- rep()
for(i in size.growth$species){
    kingdom <- unique(data$superkingdom[data$species == i])
    obj <- c(obj, kingdom)
}

size.growth$kingdom <- obj
head(size.growth)

size.growth$species <- gsub("[[:punct:]]", "", size.growth$species)
size.growth$species <- gsub(" ", "_", size.growth$species)
rownames(size.growth) <- size.growth$species
head(size.growth$species)
head(size.growth)

check <- name.check(tree, size.growth)
rm_phy <- check$tree_not_data
rm_dat <- check$data_not_tree
tree.sg <- drop.tip(tree, rm_phy)

sg.dat <- subset(size.growth, subset = size.growth$species %in% tree.sg$tip, select = names(size.growth))
name.check(tree.sg, sg.dat)
str(sg.dat)


```



<b>
<font size="5"> Prokaryote tree </font>
</b>


```{r}

#plotTree(tree.sg, type = "fan", ftype = "i", lwd = 2, mar = c(1.5, 1.5, 1.5, 1.5), fsize = 0.4)
#nodelabels(bg = "white", cex = 0.5)

col.br <- setNames(c("red", "purple"), c("Archaea", "Bacteria"))

plotTree(tree.sg, type = "fan", ftype = "off", lwd = 3)

par(new = TRUE, col = "transparent")

painted <- paintSubTree(tree.sg, 253, "Archaea" ,"0")
plotSimmap(painted, col.br, type = "fan", ftype = "off", lwd = 3)

par(new = TRUE, col = "transparent")

painted <- paintSubTree(tree.sg, 186, "Bacteria")

plotSimmap(painted, col.br, type = "fan", ftype = "off", lwd = 3)

par(new = TRUE, col = "black")

legend("topleft", legend = c("Archaea", "Bacteria"), lwd = 3, col = col.br, bty = "n")




```


<b>
<font size="5"> Size and growth within kingdoms </font>
</b>




```{r}

obj <- rep()
for(i in d1_up$species){
    kingdom <- unique(data$superkingdom[data$species == i])
    obj <- c(obj, kingdom)
}

d1_up$kingdom <- obj
head(d1_up)

d1_up$species <- gsub("[[:punct:]]", "", d1_up$species)
d1_up$species <- gsub(" ", "_", d1_up$species)
rownames(d1_up) <- d1_up$species
dim(d1_up)
head(d1_up)

size <- lm(d1_up ~ kingdom, data = d1_up)
summary(size)

## Basic boxplot

vioplot(d1_up ~ kingdom, data = d1_up, border = NA, method = "jitter", side = "right", ylab = expression(paste("Cell size")~mu*m~(log[10])), xlab = "Kingdom", col = "white", las = 1)

grid(nx = NULL, ny = NULL, col = alpha("lightgray", 0.5), lwd = 1, lty = 2)

par(new = TRUE)

vioplot(d1_up ~ kingdom, data = d1_up, border = NA, method = "jitter", side = "right", ylab = "", xlab = "", col = c(alpha("red", 0.2), alpha("purple", 0.2)), las = 1)

segments(x0 = 1, y0 = mean(d1_up$d1_up[d1_up$kingdom == "Archaea"]), x1 = 1.311, y1 = mean(d1_up$d1_up[d1_up$kingdom == "Archaea"]), lwd = 2, lty = 2, col = "blue")
text(x = 1.4, y = mean(d1_up$d1_up[d1_up$kingdom == "Archaea"]), expression(mu))

segments(x0 = 2, y0 = mean(d1_up$d1_up[d1_up$kingdom == "Bacteria"]), x1 = 2.4, y1 = mean(d1_up$d1_up[d1_up$kingdom == "Bacteria"]), lwd = 2, lty = 2, col = "blue")
text(x = 2.45, y = mean(d1_up$d1_up[d1_up$kingdom == "Bacteria"]), expression(mu))

text(x = 0.6, y = 9.8, paste("n =", length(d1_up$species), sep = " "))

#mean(d1_up$d1_up[d1_up$kingdom == "Archaea"])
#mean(d1_up$d1_up[d1_up$kingdom == "Bacteria"])

##stripchart(d1_up ~ kingdom, vertical = TRUE, data = d1_up, method = "jitter", add = TRUE, pch = 20, col = c(alpha("red", 0.3), alpha("purple", 0.5)))


```




```{r}

obj <- rep()
for(i in doubling$species){
    kingdom <- unique(data$superkingdom[data$species == i])
    obj <- c(obj, kingdom)
}

doubling$kingdom <- obj
head(doubling)

doubling$species <- gsub("[[:punct:]]", "", doubling$species)
doubling$species <- gsub(" ", "_", doubling$species)
rownames(doubling) <- doubling$species
dim(doubling)
head(doubling)

growth <- lm(doubling_h ~ kingdom, data = doubling)
summary(growth)

## Basic boxplot

vioplot(log(doubling_h) ~ kingdom, data = doubling, border = NA, method = "jitter", side = "right", ylab = "Doubling h (log)", xlab = "Kingdom", col = "white", las = 1)

grid(nx = NULL, ny = NULL, col = alpha("lightgray", 0.5), lwd = 1, lty = 2)

par(new = TRUE)

vioplot(log(doubling_h) ~ kingdom, data = doubling, border = NA, method = "jitter", side = "right", ylab = "", xlab = "", col = c(alpha("red", 0.2), alpha("purple", 0.2)), las = 1)

segments(x0 = 1, y0 = mean(log(doubling$doubling_h)[doubling$kingdom == "Archaea"]), x1 = 1.4, y1 = mean(log(doubling$doubling_h)[doubling$kingdom == "Archaea"]), lwd = 2, lty = 2, col = "blue")
text(x = 1.45, y = mean(log(doubling$doubling_h)[doubling$kingdom == "Archaea"]), expression(mu))

segments(x0 = 2, y0 = mean(log(doubling$doubling_h)[doubling$kingdom == "Bacteria"]), x1 = 2.39, y1 = mean(log(doubling$doubling_h)[doubling$kingdom == "Bacteria"]), lwd = 2, lty = 2, col = "blue")
text(x = 2.45, y = mean(log(doubling$doubling_h)[doubling$kingdom == "Bacteria"]), expression(mu))

text(x = 0.6, y = 5.8, paste("n =", length(doubling$species), sep = " "))

#mean(doubling$doubling[doubling$kingdom == "Archaea"])
#mean(doubling$doubling[doubling$kingdom == "Bacteria"])

##stripchart(doubling ~ kingdom, vertical = TRUE, data = doubling, method = "jitter", add = TRUE, pch = 20, col = c(alpha("red", 0.3), alpha("purple", 0.5)))


```




```{r}


model1 <- gls(log(doubling_h) ~ d1_up, correlation = corBrownian(phy = tree.sg, form = ~species), data = sg.dat, method = "ML")
summary(model1)

model2 <- gls(log(doubling_h) ~ d1_up*kingdom, correlation = corBrownian(phy = tree.sg, form = ~species), data = sg.dat, method = "ML")
summary(model2)

## IC

SSX <- sum(round((sg.dat$d1_up - mean(sg.dat$d1_up))^2), 2)
s2 <- var(log(sg.dat$doubling_h))
n <- length(sg.dat$doubling_h)
x <- seq(min(sg.dat$d1_up), max(sg.dat$d1_up), length = 30)
m.x <- mean(round(sg.dat$d1_up, 1))
se <- sqrt(s2*((1/n) + (((x - m.x)^2)/SSX)))
is <- qt(0.975, df = n - 2)
ii <- qt(0.025, df = n - 2)
ic.s <- se*is
ic.i <- se*ii
upper.i <- (coef(model1)[1] + coef(model1)[2]*x) + ic.s
lower.i <- (coef(model1)[1] + coef(model1)[2]*x) + ic.i




cols3 <- c(alpha("red", 0.3), alpha("purple", 0.5))[as.numeric(as.factor(sg.dat$kingdom))]

plot(log(doubling_h) ~ d1_up, data = sg.dat, xlab = expression(paste("Cell diameter")~mu*m~(log[10])), ylab = "Doubling h (log)", las = 1, pch = 21, bg = alpha("black", 0.3), cex = 1.2, type = "n")

grid(nx = NULL, ny = NULL, col = alpha("lightgray", 0.5), lwd = 1, lty = 2)

par(new = TRUE)

plot(log(doubling_h) ~ d1_up, data = sg.dat, xlab = "", ylab = "", las = 1, pch = 21, col = cols3, bg = cols3, cex = 0.8, axes = FALSE)


#lines(x = x, y = (coef(model2)[1] + coef(model2)[2]*x), lwd = 2, col = "red")
lines(x = x, y = (coef(model1)[1] + coef(model1)[2]*x), lwd = 2, col = "black")
polygon(c(rev(x), x), c(rev(lower.i), upper.i), border = FALSE, col = alpha("gold", 0.3))
#lines(x = x, y = ((coef(model2)[1] + coef(model2)[3] + coef(model2)[2] + coef(model2)[4])*x), lwd = 2, col = "purple")

legend("topright", legend = levels(as.factor((sg.dat$kingdom))), pch = 16, col = c(alpha("red", 0.3), alpha("purple", 0.5)), bg = c(alpha("red", 0.3), alpha("purple", 0.5)), bty = "n")


```


<b>
<font size="5"> Translation machinery scaling with size and growth </font>
</b>


```{r}


d1_up <- aggregate(spp.d1_up$d1_up, by = list(spp.d1_up$species), mean, na.action = na.rm)

dim(d1_up)
names(d1_up) <- c("species", "d1_up")


mrg1 <- merge(tRNA, rRNA, by = "species")
class(mrg1)
str(mrg1)

mrg.data <- merge(mrg1, d1_up, by = "species")
str(mrg.data)

obj <- rep()
for(i in mrg.data$species){
    kingdom <- unique(data$superkingdom[data$species == i])
    obj <- c(obj, kingdom)
}

mrg.data$kingdom <- obj
mrg.data$species <- gsub("[[:punct:]]", "", mrg.data$species)
mrg.data$species <- gsub(" ", "_", mrg.data$species)
rownames(mrg.data) <- mrg.data$species
length(mrg.data$species)
head(mrg.data)

check <- name.check(tree, mrg.data)
rm_phy <- check$tree_not_data
rm_dat <- check$data_not_tree
ctree <- drop.tip(tree, rm_phy)

mrg.dat <- subset(mrg.data, subset = mrg.data$species %in% ctree$tip, select = names(mrg.data))
name.check(ctree, mrg.dat)
str(mrg.dat)

model3 <- gls(rRNA ~ d1_up, correlation = corBrownian(phy = ctree, form = ~species), data = mrg.dat, method = "ML")
summary(model3)

model4 <- gls(rRNA ~ d1_up*log(tRNA), correlation = corBrownian(phy = ctree, form = ~species), data = mrg.dat, method = "ML")
summary(model4)

model5 <- gls(log(tRNA) ~ d1_up, correlation = corBrownian(phy = ctree, form = ~species), data = mrg.dat, method = "ML")
summary(model5)

```


```{r}


## Plotting rRNA vs d1_up + tRNA


layout(matrix(c(0, 0, 0, 0,
                1, 1, 2, 2,
                1, 1, 2, 2,
                0, 0, 0, 0), nrow = 4, ncol = 4, byrow = TRUE))



colors <- c(alpha("red", 0.3), alpha("purple", 0.5))[as.numeric(as.factor(mrg.dat$kingdom))]


## rRNA


SSX <- sum(round((mrg.dat$d1_up - mean(mrg.dat$d1_up))^2), 2)
s2 <- var(mrg.dat$rRNA)
n <- length(mrg.dat$rRNA)
x <- seq(min(mrg.dat$d1_up), max(mrg.dat$d1_up), length = 30)
m.x <- mean(round(mrg.dat$d1_up, 1))
se <- sqrt(s2*((1/n) + (((x - m.x)^2)/SSX)))
is <- qt(0.975, df = n - 2)
ii <- qt(0.025, df = n - 2)
ic.s <- se*is
ic.i <- se*ii
upper.i <- (coef(model3)[1] + coef(model3)[2]*x) + ic.s
lower.i <- (coef(model3)[1] + coef(model3)[2]*x) + ic.i


plot(rRNA ~ d1_up, data = mrg.dat, las = 1, pch = 21, col = colors, bg = colors, cex = 0.8, type = "n", xlab = expression(paste("Cell size")~mu*m~(log[10])), ylab = "rRNA genes")

grid(nx = NULL, ny = NULL, col = alpha("lightgray", 0.5), lwd = 1, lty = 2)

par(new = TRUE)

plot(rRNA ~ d1_up, data = mrg.dat, las = 1, pch = 21, col = colors, bg = colors, cex = 0.8, xlab = "", ylab = "", axes = FALSE)

lines(x = x, y = (coef(model3)[1] + coef(model3)[2]*x), lwd = 2, col = "black")
polygon(c(rev(x), x), c(rev(lower.i), upper.i), border = FALSE, col = alpha("gold", 0.3))

legend("topleft", legend = levels(as.factor((mrg.dat$kingdom))), pch = 16, col = c(alpha("red", 0.3), alpha("purple", 0.5)), bg = c(alpha("red", 0.3), alpha("purple", 0.5)), bty = "n")


## tRNA


SSX <- sum(round((mrg.dat$d1_up - mean(mrg.dat$d1_up))^2), 2)
s2 <- var(log(mrg.dat$tRNA))
n <- length(mrg.dat$tRNA)
x <- seq(min(mrg.dat$d1_up), max(mrg.dat$d1_up), length = 30)
m.x <- mean(round(mrg.dat$d1_up, 1))
se <- sqrt(s2*((1/n) + (((x - m.x)^2)/SSX)))
is <- qt(0.975, df = n - 2)
ii <- qt(0.025, df = n - 2)
ic.s <- se*is
ic.i <- se*ii
upper.i <- (coef(model5)[1] + coef(model5)[2]*x) + ic.s
lower.i <- (coef(model5)[1] + coef(model5)[2]*x) + ic.i


plot(log(tRNA) ~ d1_up, data = mrg.dat, las = 1, pch = 21, col = colors, bg = colors, cex = 0.8, type = "n", xlab = expression(paste("Cell size")~mu*m~(log[10])), ylab = "tRNA genes (log)")

grid(nx = NULL, ny = NULL, col = alpha("lightgray", 0.5), lwd = 1, lty = 2)

par(new = TRUE)

plot(log(tRNA) ~ d1_up, data = mrg.dat, las = 1, pch = 21, col = colors, bg = colors, cex = 0.8, xlab = "", ylab = "", axes = FALSE)

lines(x = x, y = (coef(model5)[1] + coef(model5)[2]*x), lty = 2, lwd = 2, col = "black")
polygon(c(rev(x), x), c(rev(lower.i), upper.i), border = FALSE, col = alpha("gold", 0.3))

legend("topright", legend = levels(as.factor((mrg.dat$kingdom))), pch = 16, col = c(alpha("red", 0.3), alpha("purple", 0.5)), bg = c(alpha("red", 0.3), alpha("purple", 0.5)), bty = "n")

```




```{r}


## Plotting interaction

par(mar = c(5, 4, 1.5, 3))

plot(rRNA ~ d1_up, data = mrg.dat, las = 1, pch = 21, col = colors, bg = colors, cex = 0.8, type = "n", xlab = expression(paste("Cell size")~mu*m~(log[10])), ylab = "rRNA genes")

grid(nx = NULL, ny = NULL, col = alpha("lightgray", 0.5), lwd = 1, lty = 2)

par(new = TRUE)

plot(rRNA ~ d1_up, data = mrg.dat, las = 1, pch = 21, col = colors, bg = colors, cex = 0.8, xlab = "", ylab = "", axes = FALSE)

legend(x = -0.1, y = 14.2, legend = "tRNA genes", lty = 2, lwd = 2, bty = "n")

## rRNA


SSX <- sum(round((mrg.dat$d1_up - mean(mrg.dat$d1_up))^2), 2)
s2 <- var(mrg.dat$rRNA)
n <- length(mrg.dat$rRNA)
x <- seq(min(mrg.dat$d1_up), max(mrg.dat$d1_up), length = 30)
m.x <- mean(round(mrg.dat$d1_up, 1))
se <- sqrt(s2*((1/n) + (((x - m.x)^2)/SSX)))
is <- qt(0.975, df = n - 2)
ii <- qt(0.025, df = n - 2)
ic.s <- se*is
ic.i <- se*ii
upper.i <- (coef(model3)[1] + coef(model3)[2]*x) + ic.s
lower.i <- (coef(model3)[1] + coef(model3)[2]*x) + ic.i


lines(x = x, y = (coef(model3)[1] + coef(model3)[2]*x), lwd = 2, col = "black")
polygon(c(rev(x), x), c(rev(lower.i), upper.i), border = FALSE, col = alpha("gold", 0.2))


## tRNA


par(new = TRUE)

plot(log(tRNA) ~ d1_up, data = mrg.dat, las = 1, pch = 21, col = colors, bg = colors, cex = 0.8, xlab = "", ylab = "", axes = FALSE, type = "n")

axis(side = 4, at = pretty(range(log(mrg.dat$tRNA))), las = 1)
mtext("tRNA genes (log)", side = 4, line = 2)


SSX <- sum(round((mrg.dat$d1_up - mean(mrg.dat$d1_up))^2), 2)
s2 <- var(log(mrg.dat$tRNA))
n <- length(mrg.dat$tRNA)
x <- seq(min(mrg.dat$d1_up), max(mrg.dat$d1_up), length = 30)
m.x <- mean(round(mrg.dat$d1_up, 1))
se <- sqrt(s2*((1/n) + (((x - m.x)^2)/SSX)))
is <- qt(0.975, df = n - 2)
ii <- qt(0.025, df = n - 2)
ic.s <- se*is
ic.i <- se*ii
upper.i <- (coef(model5)[1] + coef(model5)[2]*x) + ic.s
lower.i <- (coef(model5)[1] + coef(model5)[2]*x) + ic.i

lines(x = x, y = (coef(model5)[1] + coef(model5)[2]*x), lty = 2, lwd = 2, col = "black")
polygon(c(rev(x), x), c(rev(lower.i), upper.i), border = FALSE, col = alpha("gold", 0.2))

legend("topleft", legend = levels(as.factor((mrg.dat$kingdom))), pch = 16, col = c(alpha("red", 0.3), alpha("purple", 0.5)), bg = c(alpha("red", 0.3), alpha("purple", 0.5)), bty = "n")





```



```{r}


## Plotting interaction (alternative)

#plotTree(ctree, ftype = "off", type = "fan", lwd = 3)
#nodelabels(cex = 0.5, bg = "white")

col.br <- setNames(c("red", "purple"), c("Archaea", "Bacteria"))

plotTree(ctree, ftype = "off", lwd = 3, mar = c(2, 0.1, 1, 5))

par(new = TRUE, col = "transparent")

painted <- paintSubTree(ctree, 380, "Archaea" ,"0")
plotSimmap(painted, col.br, ftype = "off", lwd = 3, mar = c(2, 0.1, 1, 5))

par(new = TRUE, col = "transparent")

painted <- paintSubTree(ctree, 220, "Bacteria")
plotSimmap(painted, col.br, ftype = "off", lwd = 3, mar = c(2, 0.1, 1, 5))

par(new = TRUE, col = "black")

legend("bottomleft", legend = c("Archaea", "Bacteria"), lwd = 3, col = col.br, bty = "n")

rRNA <- setNames(mrg.dat$rRNA, rownames(mrg.dat))
tRNA <- setNames(log(mrg.dat$tRNA), rownames(mrg.dat))

par(new = TRUE)

par(mar = c(2.1, 29.7, 3, 3))

barplot(rRNA[ctree$tip.label], border = TRUE, horiz = TRUE, width = 1.065, space = 0,
        ylim = c(1, length(ctree$tip.label))-0.5, names = "", las = 2, cex.axis = 0.5, axes = FALSE)

axis(1, at = round(seq(min(rRNA), max(rRNA), length = 3), 1), labels = FALSE)
text(round(seq(min(rRNA), max(rRNA), length = 3), 2), par("usr")[3] - 0.2, labels = round(seq(min(rRNA), max(rRNA), length = 3), 1), srt = 50, pos = 1, xpd = TRUE, cex = 0.5, offset = 1)
mtext(" rRNA genes", side = 1, line = 1, cex = 0.5, font = 2)


par(new = TRUE)
par(mar = c(2.1, 32.8, 3, 0.5))

barplot(tRNA[ctree$tip.label], border = TRUE, horiz = TRUE, width = 1.065, space = 0,
        ylim = c(1, length(ctree$tip.label))-0.5, names = "", las = 2, cex.axis = 0.5, axes = FALSE)

axis(1, at = seq(0, 4.8, length = 3), labels = FALSE)
text(seq(0, 4.8, length = 3), par("usr")[3] - 0.2, labels = round(seq(min(tRNA), max(tRNA), length = 3), 1), srt = 50, pos = 1, xpd = TRUE, cex = 0.5, offset = 1)
mtext("tRNA genes", side = 1, line = 1, cex = 0.5, font = 2)



```



<b>
<font size="5"> Size and growth scaling with temperature </font>
</b>



```{r}

## Optimum temp

spp.d1_up <- data[!is.na(data$d1_up), ]
spp.temp.op <- data[!is.na(data$optimum_tmp), ]
spp.doubling <- data[!is.na(data$doubling_h), ]

d1_up <- aggregate(spp.d1_up$d1_up, by = list(spp.d1_up$species), mean, na.action = na.rm)
doubling <- aggregate(spp.doubling$doubling_h, by = list(spp.doubling$species), mean, na.action = na.rm)
temp.op <- aggregate(spp.temp.op$optimum_tmp, by = list(spp.temp.op$species), mean, na.action = na.rm)

dim(doubling)
names(doubling) <- c("species", "doubling_h")
dim(d1_up)
names(d1_up) <- c("species", "d1_up")
dim(temp.op)
names(temp.op) <- c("species", "tmp.op")

mrg.tmp.op2 <- merge(temp.op, d1_up, by = "species")
str(mrg.tmp.op2)
head(mrg.tmp.op2)
dim(mrg.tmp.op2)

mrg.tmp.op3 <- merge(mrg.tmp.op2, doubling, by = "species")
str(mrg.tmp.op3)
head(mrg.tmp.op3)
dim(mrg.tmp.op3)


obj <- rep()
for(i in mrg.tmp.op2$species){
    kingdom <- unique(data$superkingdom[data$species == i])
    obj <- c(obj, kingdom)
}

mrg.tmp.op2$kingdom <- obj
head(mrg.tmp.op2)
str(mrg.tmp.op2)


mrg.tmp.op2$species <- gsub("[[:punct:]]", "", mrg.tmp.op2$species)
mrg.tmp.op2$species <- gsub(" ", "_", mrg.tmp.op2$species)
rownames(mrg.tmp.op2) <- mrg.tmp.op2$species
head(mrg.tmp.op2$species)
head(mrg.tmp.op2)

check <- name.check(tree, mrg.tmp.op2)
rm_phy <- check$tree_not_data
rm_dat <- check$data_not_tree
tree.tmp <- drop.tip(tree, rm_phy)

tmp.dat <- subset(mrg.tmp.op2, subset = mrg.tmp.op2$species %in% tree.tmp$tip, select = names(mrg.tmp.op2))
name.check(tree.tmp, tmp.dat)
str(tmp.dat)
head(tmp.dat)



obj <- rep()
for(i in mrg.tmp.op3$species){
    kingdom <- unique(data$superkingdom[data$species == i])
    obj <- c(obj, kingdom)
}

mrg.tmp.op3$kingdom <- obj
head(mrg.tmp.op3)
str(mrg.tmp.op3)

mrg.tmp.op3$species <- gsub("[[:punct:]]", "", mrg.tmp.op3$species)
mrg.tmp.op3$species <- gsub(" ", "_", mrg.tmp.op3$species)
rownames(mrg.tmp.op3) <- mrg.tmp.op3$species
head(mrg.tmp.op3$species)
head(mrg.tmp.op3)

check <- name.check(tree, mrg.tmp.op3)
rm_phy <- check$tree_not_data
rm_dat <- check$data_not_tree
tree.tmp2 <- drop.tip(tree, rm_phy)

tmp.dat2 <- subset(mrg.tmp.op3, subset = mrg.tmp.op3$species %in% tree.tmp2$tip, select = names(mrg.tmp.op3))
name.check(tree.tmp2, tmp.dat2)
str(tmp.dat2)
head(tmp.dat2)


```




```{r}

## Cell size and temp opt

model6 <- gls(d1_up ~ log(tmp.op), correlation = corBrownian(phy = tree.tmp, form = ~species), data = tmp.dat, method = "ML")
summary(model6)


## IC

SSX <- sum(round((tmp.dat$tmp.op - mean(tmp.dat$tmp.op))^2), 2)
s2 <- var(tmp.dat$d1_up)
n <- length(tmp.dat$d1_up)
x <- seq(min(log(tmp.dat$tmp.op)), max(log(tmp.dat$tmp.op)), length = 30)
m.x <- mean(round(log(tmp.dat$tmp.op), 1))
se <- sqrt(s2*((1/n) + (((x - m.x)^2)/SSX)))
is <- qt(0.975, df = n - 2)
ii <- qt(0.025, df = n - 2)
ic.s <- se*is
ic.i <- se*ii
upper.i <- (log10(coef(model6)[1]) + log10(abs(coef(model6)[2]))*x) + ic.s
lower.i <- (log10(coef(model6)[1]) + log10(abs(coef(model6)[2]))*x) + ic.i


plot(d1_up ~ log(tmp.op), data = tmp.dat, ylab = expression(paste("Cell diameter")~mu*m~(log[10])), xlab = "Optimum temperature \u00B0C (log)", las = 1, pch = 21, cex = 1.2, type = "n")

grid(nx = NULL, ny = NULL, col = alpha("lightgray", 0.5), lwd = 1, lty = 2)

par(new = TRUE)

cols <- c(alpha("red", 0.3), alpha("purple", 0.5))[as.numeric(as.factor(tmp.dat$kingdom))]

plot(d1_up ~ log(tmp.op), data = tmp.dat, xlab = "", ylab = "", las = 1, pch = 21, col = cols, bg = cols, cex = 0.8, axes = FALSE)

lines(x = x, y = (log10(coef(model6)[1]) + log10(abs(coef(model6)[2]))*x), lwd = 2, col = "black")
polygon(c(rev(x), x), c(rev(lower.i), upper.i), border = FALSE, col = alpha("gold", 0.3))

legend("topleft", legend = levels(as.factor((tmp.dat$kingdom))), pch = 16, col = c(alpha("red", 0.3), alpha("purple", 0.5)), bg = c(alpha("red", 0.3), alpha("purple", 0.5)), bty = "n")


```


```{r}


## Doubling and temp

model7 <- gls(log(doubling_h) ~ log(tmp.op), correlation = corBrownian(phy = tree.tmp2, form = ~species), data = tmp.dat2, method = "ML")
summary(model7)


## IC

SSX <- sum(round((tmp.dat2$tmp.op - mean(tmp.dat2$tmp.op))^2), 2)
s2 <- var(log(tmp.dat2$doubling_h))
n <- length(tmp.dat2$doubling_h)
x <- seq(min(log(tmp.dat2$tmp.op)), max(log(tmp.dat2$tmp.op)), length = 30)
m.x <- mean(round(log(tmp.dat2$tmp.op), 1))
se <- sqrt(s2*((1/n) + (((x - m.x)^2)/SSX)))
is <- qt(0.975, df = n - 2)
ii <- qt(0.025, df = n - 2)
ic.s <- se*is
ic.i <- se*ii
upper.i <- (coef(model7)[1] + coef(model7)[2]*x) + ic.s
lower.i <- (coef(model7)[1] + coef(model7)[2]*x) + ic.i


plot(log(doubling_h) ~ log(tmp.op), data = tmp.dat2, ylab = "Doubling h (log)", xlab = "Optimum temperature \u00B0C (log)", las = 1, pch = 21, bg = alpha("black", 0.3), cex = 1.2, type = "n")

grid(nx = NULL, ny = NULL, col = alpha("lightgray", 0.5), lwd = 1, lty = 2)

par(new = TRUE)

cols3 <- c(alpha("red", 0.3), alpha("purple", 0.5))[as.numeric(as.factor(tmp.dat2$kingdom))]

plot(log(doubling_h) ~ log(tmp.op), data = tmp.dat2, xlab = "", ylab = "", las = 1, pch = 21, col = cols3, bg = cols3, cex = 0.8, axes = FALSE)


lines(x = x, y = (coef(model7)[1] + coef(model7)[2]*x), lty = 2, lwd = 2, col = "black")
polygon(c(rev(x), x), c(rev(lower.i), upper.i), border = FALSE, col = alpha("gold", 0.3))

legend("bottomleft", legend = levels(as.factor((tmp.dat2$kingdom))), pch = 16, col = c(alpha("red", 0.3), alpha("purple", 0.5)), bg = c(alpha("red", 0.3), alpha("purple", 0.5)), bty = "n")

#fit = phylolm(log(doubling_h) ~ log(tmp.op), data = tmp.dat2, phy = tree.tmp2, model="BM")
#summary(fit)

```


```{r}


layout(matrix(c(0, 0, 0, 0,
                1, 1, 2, 2,
                1, 1, 2, 2,
                0, 0, 0, 0), nrow = 4, ncol = 4, byrow = TRUE))

## Cell size and temp opt


## IC

SSX <- sum(round((tmp.dat$tmp.op - mean(tmp.dat$tmp.op))^2), 2)
s2 <- var(tmp.dat$d1_up)
n <- length(tmp.dat$d1_up)
x <- seq(min(log(tmp.dat$tmp.op)), max(log(tmp.dat$tmp.op)), length = 30)
m.x <- mean(round(log(tmp.dat$tmp.op), 1))
se <- sqrt(s2*((1/n) + (((x - m.x)^2)/SSX)))
is <- qt(0.975, df = n - 2)
ii <- qt(0.025, df = n - 2)
ic.s <- se*is
ic.i <- se*ii
upper.i <- (log10(coef(model6)[1]) + log10(abs(coef(model6)[2]))*x) + ic.s
lower.i <- (log10(coef(model6)[1]) + log10(abs(coef(model6)[2]))*x) + ic.i


plot(d1_up ~ log(tmp.op), data = tmp.dat, ylab = expression(paste("Cell diameter")~mu*m~(log[10])), xlab = "Optimum temperature \u00B0C (log)", las = 1, pch = 21, cex = 1.2, type = "n")

grid(nx = NULL, ny = NULL, col = alpha("lightgray", 0.5), lwd = 1, lty = 2)

par(new = TRUE)

cols <- c(alpha("red", 0.3), alpha("purple", 0.5))[as.numeric(as.factor(tmp.dat$kingdom))]

plot(d1_up ~ log(tmp.op), data = tmp.dat, xlab = "", ylab = "", las = 1, pch = 21, col = cols, bg = cols, cex = 0.8, axes = FALSE)

lines(x = x, y = (log10(coef(model6)[1]) + log10(abs(coef(model6)[2]))*x), lwd = 2, col = "black")
polygon(c(rev(x), x), c(rev(lower.i), upper.i), border = FALSE, col = alpha("gold", 0.3))

legend("topleft", legend = levels(as.factor((tmp.dat$kingdom))), pch = 16, col = c(alpha("red", 0.3), alpha("purple", 0.5)), bg = c(alpha("red", 0.3), alpha("purple", 0.5)), bty = "n")


## Doubling and temp


## IC

SSX <- sum(round((tmp.dat2$tmp.op - mean(tmp.dat2$tmp.op))^2), 2)
s2 <- var(log(tmp.dat2$doubling_h))
n <- length(tmp.dat2$doubling_h)
x <- seq(min(log(tmp.dat2$tmp.op)), max(log(tmp.dat2$tmp.op)), length = 30)
m.x <- mean(round(log(tmp.dat2$tmp.op), 1))
se <- sqrt(s2*((1/n) + (((x - m.x)^2)/SSX)))
is <- qt(0.975, df = n - 2)
ii <- qt(0.025, df = n - 2)
ic.s <- se*is
ic.i <- se*ii
upper.i <- (coef(model7)[1] + coef(model7)[2]*x) + ic.s
lower.i <- (coef(model7)[1] + coef(model7)[2]*x) + ic.i


plot(log(doubling_h) ~ log(tmp.op), data = tmp.dat2, ylab = "Doubling h (log)", xlab = "Optimum temperature \u00B0C (log)", las = 1, pch = 21, bg = alpha("black", 0.3), cex = 1.2, type = "n")

grid(nx = NULL, ny = NULL, col = alpha("lightgray", 0.5), lwd = 1, lty = 2)

par(new = TRUE)

cols3 <- c(alpha("red", 0.3), alpha("purple", 0.5))[as.numeric(as.factor(tmp.dat2$kingdom))]

plot(log(doubling_h) ~ log(tmp.op), data = tmp.dat2, xlab = "", ylab = "", las = 1, pch = 21, col = cols3, bg = cols3, cex = 0.8, axes = FALSE)


lines(x = x, y = (coef(model7)[1] + coef(model7)[2]*x), lty = 2, lwd = 2, col = "black")
polygon(c(rev(x), x), c(rev(lower.i), upper.i), border = FALSE, col = alpha("gold", 0.3))

legend("bottomleft", legend = levels(as.factor((tmp.dat2$kingdom))), pch = 16, col = c(alpha("red", 0.3), alpha("purple", 0.5)), bg = c(alpha("red", 0.3), alpha("purple", 0.5)), bty = "n")





```



```{r}


## Plotting interaction

cols <- c(alpha("red", 0.3), alpha("purple", 0.5))[as.numeric(as.factor(tmp.dat$kingdom))]
##cols3 <- c(alpha("red", 0.3), alpha("purple", 0.5))[as.numeric(as.factor(tmp.dat2$kingdom))]

par(mar = c(5, 4, 1.5, 3))


plot(d1_up ~ log(tmp.op), data = tmp.dat, ylab = expression(paste("Cell diameter")~mu*m~(log[10])), xlab = "Optimum temperature \u00B0C (log)", las = 1, pch = 21, cex = 1.2, type = "n")

grid(nx = NULL, ny = NULL, col = alpha("lightgray", 0.5), lwd = 1, lty = 2)

par(new = TRUE)

plot(d1_up ~ log(tmp.op), data = tmp.dat, xlab = "", ylab = "", las = 1, pch = 21, col = cols, bg = cols, cex = 0.8, axes = FALSE)

## IC

SSX <- sum(round((tmp.dat$tmp.op - mean(tmp.dat$tmp.op))^2), 2)
s2 <- var(tmp.dat$d1_up)
n <- length(tmp.dat$d1_up)
x <- seq(min(log(tmp.dat$tmp.op)), max(log(tmp.dat$tmp.op)), length = 30)
m.x <- mean(round(log(tmp.dat$tmp.op), 1))
se <- sqrt(s2*((1/n) + (((x - m.x)^2)/SSX)))
is <- qt(0.975, df = n - 2)
ii <- qt(0.025, df = n - 2)
ic.s <- se*is
ic.i <- se*ii
upper.i <- (log10(coef(model6)[1]) + log10(abs(coef(model6)[2]))*x) + ic.s
lower.i <- (log10(coef(model6)[1]) + log10(abs(coef(model6)[2]))*x) + ic.i

lines(x = x, y = (log10(coef(model6)[1]) + log10(abs(coef(model6)[2]))*x), lwd = 2, col = "black")
polygon(c(rev(x), x), c(rev(lower.i), upper.i), border = FALSE, col = alpha("gold", 0.3))

legend("topleft", legend = levels(as.factor((tmp.dat$kingdom))), pch = 16, col = c(alpha("red", 0.3), alpha("purple", 0.5)), bg = c(alpha("red", 0.3), alpha("purple", 0.5)), bty = "n")


## IC

SSX <- sum(round((tmp.dat2$tmp.op - mean(tmp.dat2$tmp.op))^2), 2)
s2 <- var(log(tmp.dat2$doubling_h))
n <- length(tmp.dat2$doubling_h)
x <- seq(min(log(tmp.dat2$tmp.op)), max(log(tmp.dat2$tmp.op)), length = 30)
m.x <- mean(round(log(tmp.dat2$tmp.op), 1))
se <- sqrt(s2*((1/n) + (((x - m.x)^2)/SSX)))
is <- qt(0.975, df = n - 2)
ii <- qt(0.025, df = n - 2)
ic.s <- se*is
ic.i <- se*ii
upper.i <- (coef(model7)[1] + coef(model7)[2]*x) + ic.s
lower.i <- (coef(model7)[1] + coef(model7)[2]*x) + ic.i


lines(x = x, y = (coef(model7)[1] + coef(model7)[2]*x), lty = 2, lwd = 2, col = "black")
polygon(c(rev(x), x), c(rev(lower.i), upper.i), border = FALSE, col = alpha("gold", 0.2))

axis(side = 4, at = seq(0, 10, length = 6), las = 1)
mtext("Doubling h (log)", side = 4, line = 2)

legend(x = 1.48, y = 9.5, legend = "Doubling", lty = 2, lwd = 2, bty = "n")



```

